// This file is auto-generated by scripts/pocketbase-typegen.mjs.
// Do not edit this file manually.

export interface PocketBaseSystemFields {
  id: string;
  collectionId: string;
  collectionName: string;
  created: string;
  updated: string;
}

export interface PostsRecord extends PocketBaseSystemFields {
  title: string;
  slug: string;
  excerpt: string;
  published_at: string;
  status: "draft" | "published";
  cover_image: string;
  cover_image_alt?: string;
  content?: string;
}

export interface UsersRecord extends PocketBaseSystemFields {
  password?: string;
  tokenKey?: string;
  email: string;
  emailVisibility?: boolean;
  verified?: boolean;
  name?: string;
  avatar?: string;
}

export interface PocketBaseCollections {
  posts: PostsRecord;
  users: UsersRecord;
}

export type PocketBaseCollectionName = keyof PocketBaseCollections;
export type PocketBaseCollectionRecord<TName extends PocketBaseCollectionName> =
  PocketBaseCollections[TName];
