// This file is auto-generated by scripts/pocketbase-typegen.mjs.
// Do not edit this file manually.

export interface PocketBaseSystemFields {
  id: string;
  collectionId: string;
  collectionName: string;
  created: string;
  updated: string;
}

export interface CookieConsentEventsRecord extends PocketBaseSystemFields {
  subject_key: string;
  event_type: "accept_all" | "reject_all" | "save_preferences" | "withdraw";
  preferences?: boolean;
  analytics?: boolean;
  marketing?: boolean;
  consent_version: string;
  consent_snapshot: unknown;
  locale: string;
  idempotency_key: string;
}

export interface OrganizationInvitesRecord extends PocketBaseSystemFields {
  organization: string;
  email_normalized: string;
  role: "member" | "admin";
  token_hash: string;
  expires_at: string;
  invited_by: string;
}

export interface OrganizationMembersRecord extends PocketBaseSystemFields {
  organization: string;
  user: string;
  role: "owner" | "admin" | "member";
}

export interface OrganizationsRecord extends PocketBaseSystemFields {
  name: string;
  slug: string;
  kind: "organization";
  avatar?: string;
  created_by?: string;
}

export interface PostsRecord extends PocketBaseSystemFields {
  title: string;
  slug: string;
  excerpt: string;
  published_at: string;
  status: "draft" | "published";
  cover_image: string;
  cover_image_alt?: string;
  content?: string;
  locale?: "cs" | "en";
  translation_shared_id?: string;
}

export interface UsersRecord extends PocketBaseSystemFields {
  password?: string;
  tokenKey?: string;
  email: string;
  emailVisibility?: boolean;
  verified?: boolean;
  name?: string;
  avatar?: string;
}

export interface PocketBaseCollections {
  cookie_consent_events: CookieConsentEventsRecord;
  organization_invites: OrganizationInvitesRecord;
  organization_members: OrganizationMembersRecord;
  organizations: OrganizationsRecord;
  posts: PostsRecord;
  users: UsersRecord;
}

export type PocketBaseCollectionName = keyof PocketBaseCollections;
export type PocketBaseCollectionRecord<TName extends PocketBaseCollectionName> =
  PocketBaseCollections[TName];
